<a href="https://colab.research.google.com/github/AishaEvering/TensofFlow_ComputerVision_Practice/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Basics

## Initialization

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2, 0, -3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [2, 0, -3],
    [3, 5,-1],
    [1,5,6],
    [2, 3, 8]
    ])
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -3]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
  [[1, 2, 0], [3,5,-1]],
  [[10, 2,0], [1,0,2]],
  [[5,8,0], [2,7,0]],
  [[2, 1, 9], [4,-3,32]],
 ])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [ ]:
tensor_four_d = tf.constant([[
  [[1, 2, 0], [3,5,-1]],
  [[10, 2,0], [1,0,2]],
  [[5,8,0], [2,7,0]],
  [[2, 1, 9], [4,-3,32]]
 ],
  [
  [[1, 32, 0], [3,5,-1]],
  [[10, 2,0], [1,0,2]],
  [[5,8,0], [2,57,0]],
  [[2, 41, 9], [4,-3,32]]
 ],
  [
  [[13, 2, 0], [3,55,-1]],
  [[10, 2,0], [1,0,2]],
  [[5,38,0], [2,74,0]],
  [[2, 1, 9], [4,-3,32]]
 ]])

print(tensor_four_d.shape)

(3, 4, 2, 3)


## Casting

In [ ]:
tensor_one_d = tf.constant([2,0.,-3,8,90], dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int16)

bool_casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)

print(tensor_one_d)
print(casted_tensor_one_d)
print(bool_casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello world", "hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
fill_tensor = tf.fill([3, 4],5)
fill_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int32)>

In [ ]:
ones_tensor = tf.ones([5,3])
ones_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
ones_like_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [ ]:
zeros_tensor = tf.zeros([5,3])
zeros_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.rank(zeros_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.size(fill_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
random_tensor = tf.random.normal([3,2],
                                 mean=100.0,
                                 stddev=1.0,
                                 dtype=tf.dtypes.float32,
                                 seed=None,
                                 name=None)
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 99.58031 , 101.25556 ],
       [102.109695, 100.63228 ],
       [ 98.93092 , 100.63008 ]], dtype=float32)>

In [ ]:
random_tensor = tf.random.uniform([5,],
                                 minval=0,
                                 maxval=8,
                                 dtype=tf.dtypes.float32,
                                 seed=None,
                                 name=None)
random_tensor

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([7.6254787 , 6.113373  , 0.69100666, 3.7670221 , 2.7379408 ],
      dtype=float32)>

## Indexing

In [ ]:
tensor_indexed = tf.constant([2,4,9,0,4,5,6,7])

In [ ]:
print(tensor_indexed[3])

tf.Tensor(0, shape=(), dtype=int32)


In [ ]:
print(tensor_indexed[-1])

tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
tensor_indexed[1:7]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4, 9, 0, 4, 5, 6], dtype=int32)>

In [ ]:
tensor_indexed[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 9], dtype=int32)>

In [ ]:
tensor_indexed[3:]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 4, 5, 6, 7], dtype=int32)>

In [ ]:
tensor_indexed[:7:2]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 9, 4, 6], dtype=int32)>

In [ ]:
tensor_indexed = tf.constant([[2,3,4,5,6],
                             [9,0,4,2,1],
                             [0,0,1,7,0]])

In [ ]:
tensor_indexed[1,3]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tensor_indexed[2,2:5]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 7, 0], dtype=int32)>

In [ ]:
tensor_indexed[:2,4]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 1], dtype=int32)>

In [ ]:
tensor_indexed[:,4]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 1, 0], dtype=int32)>

In [ ]:
tensor_indexed[:1,:]

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[2, 3, 4, 5, 6]], dtype=int32)>

In [ ]:
tensor_indexed[:1,...] # all the columns

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[2, 3, 4, 5, 6]], dtype=int32)>

In [ ]:
tensor_indexed[0,...] # all the columns

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
tensor_indexed[0:2,2:4]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [4, 2]], dtype=int32)>

In [ ]:
tensor_indexed = tf.constant([[[1,2,0],[3,5,-1]],
[[10,2,0],[1,0,2]],
[[5,8,0],[2,7,0]],
[[2,1,9],[4,-3,32]]])
tensor_indexed

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0]],

       [[ 2,  1,  9],
        [ 4, -3, 32]]], dtype=int32)>

In [ ]:
tensor_indexed[3,0,2]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
tensor_indexed[3,0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 1, 9], dtype=int32)>

In [ ]:
tensor_indexed[3,:,0:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  1],
       [ 4, -3]], dtype=int32)>

In [ ]:
tensor_indexed[...,:,2]

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 0, -1],
       [ 0,  2],
       [ 0,  0],
       [ 9, 32]], dtype=int32)>

## Math

In [ ]:
x = tf.constant(-0.2)
tf.abs(x)

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

In [ ]:
tf.sqrt(2.**2+3.**2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.6055512>

In [ ]:
x = tf.constant([2,3,5,7])
y = tf.constant([7,7,2,1])

tf.add(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 9, 10,  7,  8], dtype=int32)>

In [ ]:
x = tf.constant([2,3,5,7])
y = tf.constant(1)

tf.add(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 6, 8], dtype=int32)>

In [ ]:
x = tf.constant([2,3,5,7])
y = tf.constant(0)
tf.divide(x,y)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([inf, inf, inf, inf])>

In [ ]:
x = tf.constant([2,3,5,7])
y = tf.constant(0)
tf.math.divide_no_nan(x,y) # inf set to zeros

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0., 0., 0., 0.])>

In [ ]:
x = tf.constant([2,3 ,4, 5])
y = tf.constant([[1],[3]])
print(tf.math.multiply(x,y))

tf.Tensor(
[[ 2  3  4  5]
 [ 6  9 12 15]], shape=(2, 4), dtype=int32)


In [ ]:
a = tf.constant([2,20,30,3,6])
tf.math.argmax(a) # index of max value

<tf.Tensor: shape=(), dtype=int64, numpy=2>

## Linear Algebra

In [ ]:
import tensorflow as tf

a = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0],
])


b = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0],
    [7,3,0,9,0],
])

a.shape, b.shape
print(f"MatMul: {tf.linalg.matmul(a,b)}") # matrix multiplication
# not the same as a*b because this is element wise multiplication
print(f"@ symbol: {a@b}")

MatMul: [[ 95  82  43 138  17]
 [ 42  51  14  62   2]
 [ 18  17  45  41  15]
 [ 84  37  84 132  41]]
@ symbol: [[ 95  82  43 138  17]
 [ 42  51  14  62   2]
 [ 18  17  45  41  15]
 [ 84  37  84 132  41]]


In [ ]:
a = tf.constant([
    [1,5,1],
    [7,3,0],
])

tf.transpose(a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 7],
       [5, 3],
       [1, 0]], dtype=int32)>

In [ ]:
a = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0],
])


b = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0],
])

a.shape, b.shape
print(f"MatMul: {tf.linalg.matmul(a,b, transpose_b=True)}")

MatMul: [[152  92  29  78]
 [ 92  63  18  30]
 [ 29  18  31  40]
 [ 78  30  40 139]]


In [ ]:
a = tf.constant([[[1,2],[3,5]],
[[10,2],[1,0]],
[[5,8],[2,7]],
[[2,1],[4,-3]]])

b = tf.constant([[[1,2,0],[3,5,-1]],
[[10,2,0],[1,0,2]],
[[5,8,0],[2,7,0]],
[[2,1,9],[4,-3,32]]])

a.shape, b.shape

(TensorShape([4, 2, 2]), TensorShape([4, 2, 3]))

In [ ]:
tf.linalg.matmul(a,b)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[  7,  12,  -2],
        [ 18,  31,  -5]],

       [[102,  20,   4],
        [ 10,   2,   0]],

       [[ 41,  96,   0],
        [ 24,  65,   0]],

       [[  8,  -1,  50],
        [ -4,  13, -60]]], dtype=int32)>

In [ ]:
a = tf.constant([
                  [1,5,1],
                  [7,9,3],
                  [1,3,1],
])

In [ ]:
tf.linalg.band_part(a,0,0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 9, 0],
       [0, 0, 1]], dtype=int32)>

Sqaure Matrix = Number of rows should equal the number of columns


In [ ]:
a = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0],
])


b = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0],
    [7,3,0,9,0],
])

a.shape, b.shape
print(f"MatMul: {tf.linalg.matmul(a,b)}")
print(f"Einsum: {tf.einsum('ij,jk->ik',a,b)}")

MatMul: [[ 95  82  43 138  17]
 [ 42  51  14  62   2]
 [ 18  17  45  41  15]
 [ 84  37  84 132  41]]
Einsum: [[ 95  82  43 138  17]
 [ 42  51  14  62   2]
 [ 18  17  45  41  15]
 [ 84  37  84 132  41]]


In [ ]:
a = tf.constant([2,6,5,2])
b = tf.constant([0,1,3,2])

# 0+6+15+4 = 25
tf.einsum("i,i->",a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [ ]:
b = tf.constant([
    [3,1,9,6,5],
    [0,1,7,3,2],
    [1,5,1,2,0],
    [7,3,0,9,0],
])

tf.einsum("ij->ji",b) #transposed

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[3, 0, 1, 7],
       [1, 1, 5, 3],
       [9, 7, 1, 0],
       [6, 3, 2, 9],
       [5, 2, 0, 0]], dtype=int32)>

In [ ]:
a = tf.constant([
    [3,1,9,6],
    [0,1,7,3],
    [1,5,1,2],
])
b = tf.constant([
    [3,1,9,6],
    [0,1,7,3],
    [1,5,1,2],
])

In [ ]:
a*b

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 9,  1, 81, 36],
       [ 0,  1, 49,  9],
       [ 1, 25,  1,  4]], dtype=int32)>

In [ ]:
tf.einsum("ij,ij->ij",a,b)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 9,  1, 81, 36],
       [ 0,  1, 49,  9],
       [ 1, 25,  1,  4]], dtype=int32)>

## Common Methods

In [ ]:
# Expand Dims
a = tf.constant([1,3,4,5,6,7])
print(f'Shape: {a.shape}')

tf.expand_dims(a, axis=0) # now we can pass it in to a method that needs a 2D input

Shape: (6,)


<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 3, 4, 5, 6, 7]], dtype=int32)>

In [ ]:
tf.expand_dims(a, axis=1)

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [3],
       [4],
       [5],
       [6],
       [7]], dtype=int32)>

In [ ]:
# Squeeze
a = tf.constant([[1,3,4,5,6,7]])
print(f'Shape: {a.shape}')

tf.squeeze(a, axis=0) # takes away a dimension

Shape: (1, 6)


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 3, 4, 5, 6, 7], dtype=int32)>

In [ ]:
# Reshape
a = tf.constant([1,2,3,4,5,6,7,8,9])
print(f'Shape: {a.shape}')

tf.reshape(a, [3,3])

Shape: (9,)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:

tf.reshape(a, [3,-1])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
# Concat
t1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

t2 = tf.constant([
    [7, 8, 9],
    [10, 11, 12]
])

print("Shapes...", t1.shape, t2.shape, "\n")
tf.concat([t1, t2], axis=0)

Shapes... (2, 3) (2, 3) 



<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Stack
tf.stack([t1, t2], axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
# Pad
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[5, 1], # how many values to add to the top and bottom
                        [2, 4]]) # how many values to add to the left and right

tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(8, 9), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
tf.pad(t, paddings, "CONSTANT", constant_values=9)

<tf.Tensor: shape=(8, 9), dtype=int32, numpy=
array([[9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 1, 2, 3, 9, 9, 9, 9],
       [9, 9, 4, 5, 6, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int32)>

In [ ]:
# Gather
a = tf.constant([4,5,6,7])
print(a[1:3])

tf.gather(a, [0,3,1], axis=0)

tf.Tensor([5 6], shape=(2,), dtype=int32)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 7, 5], dtype=int32)>

In [ ]:
b = tf.constant([
    [2, 9, 0, 3, 0],
    [3, 6, 8, -2, 2],
    [1, 3, 5, 0, 1],
    [3, 0, 2, 0, 5]
])

tf.gather(b, [3, 0], axis=0)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[3, 0, 2, 0, 5],
       [2, 9, 0, 3, 0]], dtype=int32)>

In [ ]:
tf.gather(b, [1, 3], axis=1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 9,  3],
       [ 6, -2],
       [ 3,  0],
       [ 0,  0]], dtype=int32)>

In [ ]:
tf.gather_nd(b, [
    [1,3],
    [2,0]
])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2,  1], dtype=int32)>

In [ ]:
tf.gather_nd(b, [
    [1],
    [3]
])

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 3,  6,  8, -2,  2],
       [ 3,  0,  2,  0,  5]], dtype=int32)>

## Ragged Tensors

In [ ]:
a = tf.ragged.constant([
    [1,3],
    [4,5,6],
    [7]
])

print(a)

<tf.RaggedTensor [[1, 3], [4, 5, 6], [7]]>


In [ ]:
tf.ragged.boolean_mask(  # Mask a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([[False, False, True], [False], [True, True]])).to_list()


[[3], [], [5, 6]]

## Sparse Tensors

In [ ]:
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0,0],[2,5]],
    values=[1,9],
    dense_shape=[5,6])
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 5]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 9], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

# String Tensors

In [ ]:
tensor_string = tf.constant(['i am', 'a', 'string'])
tensor_string

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'i am', b'a', b'string'], dtype=object)>

In [ ]:
tf.strings.join(tensor_string, separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'i am+a+string'>

In [ ]:
tensor_string_1 = tf.constant(['i am', 'a', 'string'])
tensor_string_2 = tf.constant(['i am', 'not a', 'string'])
tf.strings.join([tensor_string_1, tensor_string_2], separator="+")

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'i am+i am', b'a+not a', b'string+string'], dtype=object)>

## Variables

In [ ]:
x = tf.constant([1,2,3,4,5])
x_var = tf.Variable(x)
print(x, x_var,sep="\n")

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>


In [ ]:
x_var.assign_add([5, 5, 5, 5, 5]) # is doesn't broadcast

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>

In [ ]:
x_var.assign_sub([5, 5, 5, 5, 5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
x_var.assign([5, 5, 5, 5, 5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([5, 5, 5, 5, 5], dtype=int32)>